### ISSUE TITLE
Update some dependency packages

### ISSUE THREAD

**Issue by lathamios** [sendbird/Sendbird-Flutter#4]
Would it be possible to update some of the dependencies to newer versions?

e.g. http to http ^0.13.0, image_picker to image_picker: ^0.7.4, shared_preference to shared_preferences: ^2.0.5

Otherwise it make upgrading other packages (e.g google maps) very difficult

Thanks!

**Comment by intoxicated** [comment]
packages you mentioned are depending on flutter 2 unfortunately. We will plan to migrate flutter 1 to flutter 2 soon!

**Comment by lathamios** [comment]
Great! I am currently running flutter 2 with your latest coded and it seems to work fine

**Comment by intoxicated** [comment]
it should work with `--no-sound-null-safety` argument.

**Comment by lathamios** [comment]
Ok @intoxicated I will give it a go! Thanks!

**Comment by splex7** [comment]
Hi there.

https://sendbird.com/developer/tutorials/sendbird-flutter-3rd-party-ui 
this tutorial need to be update. this is related with null-safety update.

Due to a null-saftety issue, a package error will occur if you do not explicitly specify the flutter SDK version in Tutorial.
`
//pubspec.yaml
environment:
  sdk: ">=2.12.0 <3.0.0" //  Generated by Flutter:new application project. 
  sdk: ">=2.7.0 <3.0.0" //  It should be mentioned in the tutorial that this should be modified.
` 

I am waiting for the null-safety applied example to be updated.

**Comment by jalakoo** [comment]
Thanks @splex7 I'll update the tutorial with the non null-safety versioning requirement.

**Comment by intoxicated** [comment]
@lathamios just released `3.0.14-nullsafety` before we go for official release. Its still pre-release but I believe It would be enough for you to proceed.
